import React from "react";
import { ResourceProps } from "@refinedev/core";
import {
  BellOutlined, WarningOutlined, FileProtectOutlined,
  MedicineBoxOutlined, ReadOutlined, GlobalOutlined,
  BarcodeOutlined, WalletOutlined, UserOutlined,
  TeamOutlined, BookOutlined, SyncOutlined, RocketOutlined,
  SettingOutlined, FormOutlined, ProjectOutlined,
  DashboardOutlined, BankOutlined, ShoppingCartOutlined,
  SafetyCertificateOutlined, HistoryOutlined,
  DatabaseOutlined, MessageOutlined, ShopOutlined,
  TrophyOutlined, BarChartOutlined, CalendarOutlined,
} from "@ant-design/icons";

export const resources: ResourceProps[] = [
  { name:"dashboard", list:"/", meta:{ label:"Dashboard", icon:<DashboardOutlined /> } },

  { name:"data_pesantren_menu", meta:{ label:"Data Pesantren", icon:<BankOutlined /> } },
  { name:"instansi_info", list:"/instansi",
    meta:{ label:"Profil", parent:"data_pesantren_menu", icon:<BankOutlined /> } },
  { name:"admin_management", list:"/admin-management/list", create:"/admin-management/create",
    meta:{ label:"Admin", parent:"data_pesantren_menu", icon:<UserOutlined /> } },
  { name:"santri", list:"/santri", create:"/santri/create", edit:"/santri/edit/:id", show:"/santri/show/:id",
    meta:{ label:"Data Santri", parent:"data_pesantren_menu", icon:<UserOutlined />, idColumnName:"nis" } },
  { name:"persebaran_santri", list:"/persebaran-santri",
    meta:{ label:"Persebaran", parent:"data_pesantren_menu", icon:<GlobalOutlined /> } },

  { name:"akademik_menu", meta:{ label:"Akademik", icon:<BookOutlined /> } },
  { name:"akademik", list:"/akademik",
    meta:{ label:"Laporan Nilai", parent:"akademik_menu", icon:<BookOutlined /> } },
  { name:"ulangan_menu", meta:{ label:"Ulangan Mingguan", parent:"akademik_menu", icon:<FormOutlined /> } },
  { name:"weekly_tests", list:"/ulangan", create:"/ulangan/create",
    meta:{ label:"Bank Ulangan", parent:"ulangan_menu", icon:<ProjectOutlined /> } },
  { name:"ulangan_arsip", list:"/ulangan/arsip",
    meta:{ label:"Arsip & Nilai", parent:"ulangan_menu", icon:<FileProtectOutlined /> } },
  { name:"tahfidz_menu", meta:{ label:"Takhasus", icon:<ReadOutlined /> } },
  { name:"hafalan_tahfidz", list:"/hafalan", create:"/hafalan/create", edit:"/hafalan/edit/:id", show:"/hafalan/show/:id",
    meta:{ label:"Ziyadah (Baru)", parent:"tahfidz_menu", icon:<BookOutlined /> } },
  { name:"murojaah_tahfidz", list:"/murojaah", create:"/murojaah/create", show:"/murojaah/show/:id",
    meta:{ label:"Murojaah (Ulang)", parent:"tahfidz_menu", icon:<SyncOutlined /> } },
  { name:"tahfidz_rekap", list:"/hafalan/rekap",
    meta:{ label:"Rekap Tahfidz", parent:"tahfidz_menu", icon:<BarChartOutlined /> } },
  { name:"hafalan_kitab", list:"/hafalan-kitab", create:"/hafalan-kitab/create", show:"/hafalan-kitab/show/:id",
    meta:{ label:"Hafalan Kitab", parent:"tahfidz_menu", icon:<BookOutlined /> } },
  { name:"mingguan_absensi", list:"/tahfidz/mingguan",
    meta:{ label:"Mingguan", parent:"tahfidz_menu", icon:<CalendarOutlined /> } },
  { name:"ngaji_absensi", list:"/tahfidz/ngaji",
    meta:{ label:"Ngaji", parent:"tahfidz_menu", icon:<ReadOutlined /> } },
  { name:"sholat_hifdzi_absensi", list:"/tahfidz/sholat-hifdzi",
    meta:{ label:"Sholat Hifdzi", parent:"tahfidz_menu", icon:<CalendarOutlined /> } },
  { name:"diklat", meta:{ label:"Diklat & Pasaran", parent:"akademik_menu", icon:<RocketOutlined /> } },
  { name:"diklat_list", list:"/diklat",
    meta:{ label:"Daftar Peserta", parent:"diklat", icon:<TeamOutlined /> } },
  { name:"diklat_master", list:"/diklat/master",
    meta:{ label:"Master Data Diklat", parent:"diklat", icon:<SettingOutlined /> } },

  { name:"kesantrian_menu", meta:{ label:"Kesantrian", icon:<TeamOutlined /> } },
  // Menu "Absensi Santri" dan "Tipe Kegiatan" disembunyikan sementara
  // { name:"attendance_sessions", list:"/absensi", show:"/absensi/show/:id",
  //   meta:{ label:"Absensi Santri", parent:"kesantrian_menu", icon:<ProjectOutlined /> } },
  // { name:"attendance_types", list:"/absensi/types",
  //   meta:{ label:"Tipe Kegiatan", parent:"kesantrian_menu", icon:<SettingOutlined /> } },
  { name:"pelanggaran_santri", list:"/pelanggaran", create:"/pelanggaran/create", edit:"/pelanggaran/edit/:id",
    meta:{ label:"Pelanggaran", parent:"kesantrian_menu", icon:<WarningOutlined /> } },
  { name:"perizinan_santri", list:"/perizinan", create:"/perizinan/create", edit:"/perizinan/edit/:id",
    meta:{ label:"Perizinan", parent:"kesantrian_menu", icon:<FileProtectOutlined /> } },
  { name:"kesehatan_santri", list:"/kesehatan", create:"/kesehatan/create", edit:"/kesehatan/edit/:id",
    meta:{ label:"Kesehatan (UKS)", parent:"kesantrian_menu", icon:<MedicineBoxOutlined /> } },
  { name:"prestasi_santri", list:"/prestasi",
    meta:{ label:"Prestasi Santri", parent:"kesantrian_menu", icon:<TrophyOutlined /> } },

  { name:"keuangan_menu", meta:{ label:"Keuangan", icon:<WalletOutlined /> } },
  { name:"ref_jenis_pembayaran", list:"/jenis-pembayaran",
    meta:{ label:"Master Pembayaran", parent:"keuangan_menu", icon:<SettingOutlined /> } },
  { name:"tagihan_santri", list:"/tagihan", create:"/tagihan/create", edit:"/tagihan/edit/:id",
    meta:{ label:"Tagihan & SPP", parent:"keuangan_menu", icon:<WalletOutlined /> } },
  { name:"transaksi_keuangan", list:"/transaksi", create:"/transaksi/create",
    meta:{ label:"Riwayat Transaksi", parent:"keuangan_menu", icon:<HistoryOutlined /> } },
  { name:"pengeluaran", list:"/pengeluaran",
    meta:{ label:"Pengeluaran", parent:"keuangan_menu", icon:<ShoppingCartOutlined /> } },

  { name:"dompet_menu", meta:{ label:"Dompet & Kantin", icon:<WalletOutlined /> } },
  { name:"dompet_santri", list:"/dompet-santri",
    meta:{ label:"Akun & Saldo", parent:"dompet_menu", icon:<WalletOutlined /> } },
  { name:"dompet_operasional", list:"/dompet-operasional",
    meta:{ label:"Operasional", parent:"dompet_menu", icon:<SafetyCertificateOutlined /> } },
  { name:"kantin_management", list:"/kantin-management",
    meta:{ label:"Manajemen Kantin", parent:"dompet_menu", icon:<ShopOutlined /> } },
  { name:"dompet_security_audit", list:"/dompet-security-audit",
    meta:{ label:"Audit Dompet", parent:"dompet_menu", icon:<DatabaseOutlined /> } },

  { name:"komunikasi_menu", meta:{ label:"Komunikasi", icon:<BellOutlined /> } },
  { name:"berita", list:"/berita", create:"/berita/create", edit:"/berita/edit/:id",
    meta:{ label:"Berita", parent:"komunikasi_menu", icon:<GlobalOutlined /> } },
  { name:"notification_queue", list:"/notifications", create:"/notifications/create",
    meta:{ label:"Notifikasi", parent:"komunikasi_menu", icon:<BellOutlined /> } },
  { name:"rag_knowledge", list:"/rag",
    meta:{ label:"RAG Knowledge", parent:"komunikasi_menu", icon:<DatabaseOutlined /> } },

  { name:"alumni_menu", meta:{ label:"Alumni", icon:<TeamOutlined /> } },
  { name:"alumni_data",  list:"/alumni",      meta:{ label:"Data Alumni", parent:"alumni_menu", icon:<GlobalOutlined /> } },
  { name:"forum_moderation_actions", list:"/forum-alumni", meta:{ label:"Moderasi Forum", parent:"alumni_menu", icon:<MessageOutlined /> } },
  { name:"forum_reports", list:"/forum-reports", meta:{ label:"Laporan Forum", parent:"alumni_menu", icon:<SafetyCertificateOutlined /> } },
  { name:"chat_monitoring", list:"/chat-alumni", meta:{ label:"Laporan Chat", parent:"alumni_menu", icon:<MessageOutlined /> } },

  { name:"operasional_menu", meta:{ label:"Operasional", icon:<BarcodeOutlined /> } },
  { name:"inventaris", list:"/inventaris", create:"/inventaris/create",
    edit:"/inventaris/edit/:id", show:"/inventaris/show/:id",
    meta:{ label:"Inventaris Aset", parent:"operasional_menu", icon:<BarcodeOutlined /> } },
  { name:"scan-qr", list:"/scanQr",
    meta:{ label:"Scan QR", parent:"operasional_menu", icon:<BarcodeOutlined /> } },

  { name:"sistem_menu", meta:{ label:"Sistem", icon:<SafetyCertificateOutlined /> } },
  { name:"audit_logs", list:"/audit-logs",
    meta:{ label:"Log Aktivitas", parent:"sistem_menu", icon:<SafetyCertificateOutlined /> } },
  { name:"koreksi_hijriah", list:"/koreksi-hijriah",
    meta:{ label:"Koreksi Hijriah", parent:"sistem_menu", icon:<CalendarOutlined /> } },
  { name:"backend_command_center", meta:{ label:"Backend Center", parent:"sistem_menu", icon:<DatabaseOutlined /> } },
  { name:"backend_self_healing", list:"/backend-command-center/self-healing",
    meta:{ label:"Self-Healing", parent:"backend_command_center", icon:<SafetyCertificateOutlined /> } },
  { name:"backend_diagnostics", list:"/backend-command-center/diagnostics",
    meta:{ label:"Diagnostics", parent:"backend_command_center", icon:<DatabaseOutlined /> } },
  { name:"backend_private_audit_log", list:"/backend-command-center/private-audit-log",
    meta:{ label:"Private Audit", parent:"backend_command_center", icon:<FileProtectOutlined /> } },
];
