import React from "react";
import { ResourceProps } from "@refinedev/core";
import {
  BellOutlined, WarningOutlined, FileProtectOutlined,
  MedicineBoxOutlined, ReadOutlined, GlobalOutlined,
  BarcodeOutlined, WalletOutlined, UserOutlined,
  TeamOutlined, BookOutlined, SyncOutlined, RocketOutlined,
  SettingOutlined, FormOutlined, ProjectOutlined,
  DashboardOutlined, BankOutlined, ShoppingCartOutlined,
  SafetyCertificateOutlined, HistoryOutlined,
  DatabaseOutlined, MessageOutlined, ShopOutlined,
} from "@ant-design/icons";

export const resources: ResourceProps[] = [
  { name:"dashboard",      list:"/",         meta:{ label:"Dashboard",                icon:<DashboardOutlined /> } },
  { name:"instansi_info",  list:"/instansi", meta:{ label:"Profil Pesantren",          icon:<BankOutlined /> } },
  { name:"admin_management", list:"/admin-management/list", create:"/admin-management/create",
    meta:{ label:"Manajemen Admin", icon:<UserOutlined /> } },
  { name:"santri", list:"/santri", create:"/santri/create", edit:"/santri/edit/:id", show:"/santri/show/:id",
    meta:{ label:"Data Santri", icon:<UserOutlined />, idColumnName:"nis" } },
  { name:"persebaran_santri", list:"/persebaran-santri",
    meta:{ label:"Persebaran Santri", icon:<GlobalOutlined /> } },
  { name:"berita", list:"/berita", create:"/berita/create", edit:"/berita/edit/:id",
    meta:{ label:"Informasi & Berita", icon:<GlobalOutlined /> } },
  { name:"kesantrian_menu", meta:{ label:"Kesantrian", icon:<TeamOutlined /> } },
  { name:"pelanggaran_santri", list:"/pelanggaran", create:"/pelanggaran/create", edit:"/pelanggaran/edit/:id",
    meta:{ label:"Pelanggaran", parent:"kesantrian_menu", icon:<WarningOutlined /> } },
  { name:"perizinan_santri", list:"/perizinan", create:"/perizinan/create", edit:"/perizinan/edit/:id",
    meta:{ label:"Perizinan", parent:"kesantrian_menu", icon:<FileProtectOutlined /> } },
  { name:"kesehatan_santri", list:"/kesehatan", create:"/kesehatan/create", edit:"/kesehatan/edit/:id",
    meta:{ label:"Kesehatan (UKS)", parent:"kesantrian_menu", icon:<MedicineBoxOutlined /> } },
  { name:"tahfidz_menu", meta:{ label:"Tahfidz Quran", icon:<ReadOutlined /> } },
  { name:"hafalan_tahfidz", list:"/hafalan", create:"/hafalan/create", edit:"/hafalan/edit/:id", show:"/hafalan/show/:id",
    meta:{ label:"Ziyadah (Baru)", parent:"tahfidz_menu", icon:<BookOutlined /> } },
  { name:"murojaah_tahfidz", list:"/murojaah", create:"/murojaah/create", show:"/murojaah/show/:id",
    meta:{ label:"Murojaah (Ulang)", parent:"tahfidz_menu", icon:<SyncOutlined /> } },
  { name:"hafalan_kitab", list:"/hafalan-kitab", create:"/hafalan-kitab/create", show:"/hafalan-kitab/show/:id",
    meta:{ label:"Hafalan Kitab", parent:"tahfidz_menu", icon:<BookOutlined /> } },
  { name:"alumni_menu", meta:{ label:"ALUMNI", icon:<TeamOutlined /> } },
  { name:"alumni_data",  list:"/alumni",      meta:{ label:"Data Alumni", parent:"alumni_menu", icon:<GlobalOutlined /> } },
  { name:"forum_threads", list:"/forum-alumni", meta:{ label:"Forum", parent:"alumni_menu", icon:<MessageOutlined /> } },
  { name:"forum_reports", list:"/forum-reports", meta:{ label:"Laporan Forum", parent:"alumni_menu", icon:<SafetyCertificateOutlined /> } },
  { name:"chat_monitoring", list:"/chat-alumni", meta:{ label:"Laporan Chat", parent:"alumni_menu", icon:<MessageOutlined /> } },
  { name:"audit_logs",   list:"/audit-logs",  meta:{ label:"Log Aktivitas (Permanen)",     icon:<SafetyCertificateOutlined /> } },
  { name:"rag_knowledge", list:"/rag",         meta:{ label:"RAG Knowledge Base",           icon:<DatabaseOutlined /> } },
  { name:"akademik",     list:"/akademik",    meta:{ label:"Laporan Nilai",                icon:<BookOutlined /> } },
  { name:"tagihan_santri", list:"/tagihan", create:"/tagihan/create", edit:"/tagihan/edit/:id",
    meta:{ label:"Keuangan & SPP", icon:<WalletOutlined /> } },
  { name:"transaksi_keuangan", list:"/transaksi", create:"/transaksi/create",
    meta:{ label:"Riwayat Transaksi", icon:<HistoryOutlined /> } },
  { name:"dompet_santri", list:"/dompet-santri",
    meta:{ label:"Dompet Santri", icon:<WalletOutlined /> } },
  { name:"kantin_management", list:"/kantin-management",
    meta:{ label:"Manajemen Kantin", icon:<ShopOutlined /> } },
  { name:"diklat", meta:{ label:"Diklat & Pasaran", icon:<RocketOutlined /> } },
  { name:"diklat_list",   list:"/diklat",        meta:{ label:"Daftar Peserta",     parent:"diklat", icon:<TeamOutlined /> } },
  { name:"diklat_master", list:"/diklat/master", meta:{ label:"Master Data Diklat", parent:"diklat", icon:<SettingOutlined /> } },
  { name:"pengeluaran",  list:"/pengeluaran", meta:{ label:"Pengeluaran", icon:<ShoppingCartOutlined /> } },
  { name:"scan-qr",      list:"/scanQr",      meta:{ label:"Scan QR",     icon:<BarcodeOutlined /> } },
  { name:"inventaris", list:"/inventaris", create:"/inventaris/create",
    edit:"/inventaris/edit/:id", show:"/inventaris/show/:id",
    meta:{ label:"Inventaris Aset", icon:<BarcodeOutlined /> } },
  { name:"ulangan_menu", meta:{ label:"Ulangan Mingguan", icon:<FormOutlined /> } },
  { name:"weekly_tests", list:"/ulangan", create:"/ulangan/create",
    meta:{ label:"Bank & Buat Ulangan", parent:"ulangan_menu", icon:<ProjectOutlined /> } },
  { name:"ulangan_arsip", list:"/ulangan/arsip",
    meta:{ label:"Arsip & Nilai", parent:"ulangan_menu", icon:<FileProtectOutlined /> } },
  { name:"notification_queue", list:"/notifications", create:"/notifications/create",
    meta:{ label:"Notifikasi Push", icon:<BellOutlined /> } },
];
